export enum TipoMovimiento {
  SALIDA_VENTA = 'SALIDA_VENTA',
  ENTRADA_ANULACION = 'ENTRADA_ANULACION',
  AJUSTE_MANUAL_ENTRADA = 'AJUSTE_MANUAL_ENTRADA',
  AJUSTE_MANUAL_SALIDA = 'AJUSTE_MANUAL_SALIDA',
}